name: Dependencies check NPM

on:
  push:
  workflow_dispatch:

jobs:
  dependencies_check_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn
      - name: Yarn Outdated
        run: yarn outdated
